### PR TITLE
Add a "test server" section to the readme

### PR DESCRIPTION
**Pull request by chmac**
Follow up from #125 adding a note about the data directory and advice on how to run a "test" installation without affecting any system wide paths.

### CODE REVIEW

**Comment by WardCunningham** [comment]
I wonder if we can improve on @chmac's addition by adding recommended parameters for security configuration and maybe even default neighbors? What advice would give a github/node user the best out-of-box experience?

**Comment by chmac** [comment]
@WardCunningham Absolutely, I'm sure you'll be able to improve on it. I'd say a key message is that a node user expects a node_module to be *local*. When it starts accessing system wide paths, that's unexpected to the average node user in my opinion.

It seems like y'all are using `npm` as a distribution mechanism for an "application" rather than a "package", which makes sense, I can understand the logic.

One of my first questions was "can't I just clone this repo and run it?" Maybe something could be added explaining how to do that if it's possible.

**Comment by WardCunningham** [comment]
Yes, we develop with local repo using `npm link` to bring in whatever wiki plugin we happen to be working on. Then `npm publish` our work and install it everywhere with Plugmatic which wraps npm.

http://ward.asia.wiki.org/view/about-plugmatic-plugin/view/more-about-plugmatic-plugin

**Comment by paul90** [comment]
Thank you Callum, I have added a note about needing to install using `global-style` so wiki finds its components in the expected relative location when not installing globally.

**Pull request merged**
